version: "3.1"
services:
    server:
        build: server/
        command: python ./server.py
        ports:
            - 1234:1234
#    client:
#        build: client/
#        command: python ./client.py
#        network_mode: host
#        depends_on:
#            - server
#    db:
#        image: mysql
#        command: --default-authentication-plugin=mysql_native_password
#        restart: always
#        environment:
#            MYSQL_ROOT_PASSWORD: example

#    adminer:
#        image: adminer
#        restart: always
#        ports:
#            - 8080:8080
#        depends_on:
#            - db


